### ISSUE TITLE
Baked lightmap broken

### ISSUE THREAD

**Issue by QuentinNev** [Hello-Meow/ModTool#8]
Hi !

We're currently using ModTool (and it's a fantastic tool !) but we encountered an issue upon exporting scene with baked lightmap. When we load the scene, the terrain is entirely black. It does this only with builded game, in editor everything is fine.

Have you any idea what could cause this issue ?

Thank you in advance.

**Comment by Hello-Meow** [comment]
Hi, 

This might be because the built game does not have have the required shaders. In the editor, all shaders are available, so it works. When building the game, Unity only includes the required shaders, so it stops working. 

To include the required shaders, go to Project Settings > Graphics and then go down to Shader Stripping. Here you can select Custom for Lightmap Modes. If you leave everything checked, it should include all shaders.

**Comment by QuentinNev** [comment]
Actually we found a solution, we disabled Lightmap Steaming under Player > Other Settings.
We're waiting some confirmations from our community but I'm gonna try your solution tomorrow and tell you if it worked too.

Thank you for your quick reply !

**Comment by QuentinNev** [comment]
After some test, your solution is better although it greatly increase build time. (maybe including every lightmap shader wasn't the best idea)

Issue solved ! Thank you !
